// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRZ7MEuQ-8Ro5Bx3rhx47qIFodD-6dLQ0',
    appId: '1:40790253747:web:2897b2237f68374456d0c6',
    messagingSenderId: '40790253747',
    projectId: 'fir-db-c95d1',
    authDomain: 'fir-db-c95d1.firebaseapp.com',
    storageBucket: 'fir-db-c95d1.firebasestorage.app',
    measurementId: 'G-RTZ1HKFR57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuWskN6UJxQDpnmztQGQ270rG3eNS-ayo',
    appId: '1:40790253747:android:caae33695c5cf50656d0c6',
    messagingSenderId: '40790253747',
    projectId: 'fir-db-c95d1',
    storageBucket: 'fir-db-c95d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzfgRqHnsegWgTuuh5-BAfjr0P-Kw_rQY',
    appId: '1:40790253747:ios:5b46be61e08c55f956d0c6',
    messagingSenderId: '40790253747',
    projectId: 'fir-db-c95d1',
    storageBucket: 'fir-db-c95d1.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzfgRqHnsegWgTuuh5-BAfjr0P-Kw_rQY',
    appId: '1:40790253747:ios:5b46be61e08c55f956d0c6',
    messagingSenderId: '40790253747',
    projectId: 'fir-db-c95d1',
    storageBucket: 'fir-db-c95d1.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRZ7MEuQ-8Ro5Bx3rhx47qIFodD-6dLQ0',
    appId: '1:40790253747:web:5511101cc5ab96d856d0c6',
    messagingSenderId: '40790253747',
    projectId: 'fir-db-c95d1',
    authDomain: 'fir-db-c95d1.firebaseapp.com',
    storageBucket: 'fir-db-c95d1.firebasestorage.app',
    measurementId: 'G-LBB9FGHV82',
  );
}
