import 'package:flutter/material.dart';
import 'package:provider/provider.dart'; // <-- add this
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

import './pages/loading.dart';
import './pages/home.dart';
import './pages/Notes.dart';
import './pages/login.dart';

import './providers/task_provider.dart'; // <-- add this
import 'firebase_options.dart';
import './pages/calender.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(
    //with this changeNotifier Provider all
    ChangeNotifierProvider(
      //here we create a context with the class we created in the provider page
      create: (context) => TaskProvider(), // <-- add provider
      child: MaterialApp(
        initialRoute: '/login',
        routes: {
          '/': (context) => Loading(),
          '/home': (context) => Home(),
          '/note': (context) => Note(),
          '/login': (context) => Login(),
        },
      ),
    ),
  );
}
